spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
  h2:
    console:
      enabled: true
jwt:
  issuer: hyojin202406@gmail.com
  secret_key: study-springboot