spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/projectx?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
  h2:
    console:
      enabled: true
jwt:
  issuer: hyojin202406@gmail.com
  secret_key: study-springboot

file:
  upload-dir: C:/study/image